name: Deploy MultiDocker
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t standen1/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true standen1/react-test npm test

      - run: docker build -t standen1/multi-client ./client
      - run: docker build -t standen1/multi-nginx ./nginx
      - run: docker build -t standen1/multi-server ./server
      - run: docker build -t standen1/multi-worker ./worker

      - run: docker push standen1/multi-client
      - run: docker push standen1/multi-nginx
      - run: docker push standen1/multi-server
      - run: docker push standen1/multi-worker